pncp:
  target: dev
  outputs:
    dev:
      type: postgres
      host: pncp_postgres  # <--- Nome direto do serviço no compose
      port: 5432
      user: postgres
      password: postgres
      dbname: pncp_db
      schema: gold
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
